curwd <- getwd()
on.exit(setwd(curwd))
dest <- file.path(R_PACKAGE_DIR, paste0('bin', R_ARCH))
dir.create(dest, recursive = TRUE, showWarnings = FALSE)
setwd(dest)
system('git clone https://github.com/google/REAPER.git')
setwd('REAPER')
dir.create('build')
setwd('build')
system('cmake ..')
system('make')
exec <- 'reaper'
if (WINDOWS) exec <- paste0(exec, '.exe')
file.rename(exec, paste0(dest, '/', exec))
setwd(dest)
unlink('REAPER', recursive = TRUE, force = TRUE)
setwd(curwd)
