// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// reaper_wrap
List reaper_wrap(IntegerVector samples, double sample_rate, double f0min, double f0max, bool suppress_highpass_filter, bool hilbert, double interval, double unvoiced_cost, double unvoiced_pulse_interval, bool verbose);
RcppExport SEXP _reapeR_reaper_wrap(SEXP samplesSEXP, SEXP sample_rateSEXP, SEXP f0minSEXP, SEXP f0maxSEXP, SEXP suppress_highpass_filterSEXP, SEXP hilbertSEXP, SEXP intervalSEXP, SEXP unvoiced_costSEXP, SEXP unvoiced_pulse_intervalSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< double >::type sample_rate(sample_rateSEXP);
    Rcpp::traits::input_parameter< double >::type f0min(f0minSEXP);
    Rcpp::traits::input_parameter< double >::type f0max(f0maxSEXP);
    Rcpp::traits::input_parameter< bool >::type suppress_highpass_filter(suppress_highpass_filterSEXP);
    Rcpp::traits::input_parameter< bool >::type hilbert(hilbertSEXP);
    Rcpp::traits::input_parameter< double >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< double >::type unvoiced_cost(unvoiced_costSEXP);
    Rcpp::traits::input_parameter< double >::type unvoiced_pulse_interval(unvoiced_pulse_intervalSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(reaper_wrap(samples, sample_rate, f0min, f0max, suppress_highpass_filter, hilbert, interval, unvoiced_cost, unvoiced_pulse_interval, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_reapeR_reaper_wrap", (DL_FUNC) &_reapeR_reaper_wrap, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_reapeR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
