# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Wrap REAPER C++ library
#'
#' Low-level wrapper for calling REAPER's `epoch_tracker` procedure
#'
#' @param samples Numeric vector giving audio samples in 16-bit integer format.
#' @param sample_rate Numeric giving the sampling rate of `samples`.
#' @param f0min Numeric value specifying pitch floor. Default is `40`.
#' @param f0max Numeric value specifying pitch ceiling. Default is `500`.
#' @param suppress_highpass_filter Boolean; should highpass filter be
#' suppressed? Default is `FALSE`.
#' @param hilbert Boolean; should Hilbert transform be applied prior to
#' analysis? Default is `FALSE`.
#' @param interval Numeric value giving the F0 output interval in seconds.
#' Default is `0.005`.
#' @param unvoiced_cost Numeric; cost for unvoiced segments. Default is `0.9`,
#' set higher value to estimate more F0 in noise.
#' @param unvoiced_pulse_interval Numeric; what should be the interval in
#' seconds of epoch pulses outside of voiced intervals? Default is `0.01`.
#' @param verbose Boolean; should messages be printed to the console?
#'
#' @returns A list object with five elements: `epochs` gives the location
#' of (voiced and unvoiced) epochs; `voicing` (same length as epochs) gives
#' information about whether epochs are voiced; `f0` gives estimated pitch;
#' `correlation` gives correlation between pitch estiamtes; `f0_interval`
#' returns the value of `interval`.
#' @export
#'
#' @examples
#' file <- file.path(system.file('extdata', package = 'reapeR'), '1.wav')
#' snd <- tuneR::readWave(file)
#' results <- reaper_wrap(snd@left, snd@samp.rate)
reaper_wrap <- function(samples, sample_rate, f0min = 40.0, f0max = 500.0, suppress_highpass_filter = FALSE, hilbert = FALSE, interval = 0.005, unvoiced_cost = 0.9, unvoiced_pulse_interval = 0.01, verbose = FALSE) {
    .Call(`_reapeR_reaper_wrap`, samples, sample_rate, f0min, f0max, suppress_highpass_filter, hilbert, interval, unvoiced_cost, unvoiced_pulse_interval, verbose)
}

